CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
VALUES('Make a web app', 1, 'Using javascript', '2022-02-16'),
      ('Make an app', 1, 'Using Dart', '2022-02-17'),
      ('Make a desktop app', 2, 'Using C#', '2022-02-14');

INSERT INTO tasks(name, done, projectID)
VALUES('Download vuejs', false, 1),
      ('Create UI web', false, 1),
      ('Download flutter', false, 2),
      ('Design UI web', false, 2),
      

